### ISSUE TITLE
Publish types for censys responses

### ISSUE THREAD

**Issue by epicfaace** [censys/censys-node-js#23]
This library is great! It would be great if you could also publish typings with this library, especially for API responses.

We made a small script here (https://github.com/cisagov/crossfeed/blob/master/backend/src/tools/generate-censys-types.ts) to do that by converting the public bigquery schemas to JSON Schemas and then to typescript types. This helped us to generate https://github.com/cisagov/crossfeed/blob/master/backend/src/models/generated/censysCertificates.ts and https://github.com/cisagov/crossfeed/blob/master/backend/src/models/generated/censysIpv4.ts

Let me know if you're interested in doing this.

**Comment by thehappydinoa** [comment]
Hi there! This is such a great idea, I currently have an PR (#11) for fully supporting types. I can't promise I will use this tool, but I did want to let you know that we do accept PRs. The branch is `adh/typescript`. Also I will be turning this into a discussion.
